version: '3.4'

services:
  #handwritting:
    #image: handwritting
    #build:
      #context: .
      #dockerfile: ./Dockerfile
    #environment:
      #NODE_ENV: production
    #ports:
      #- 3000:3000
# name of our dockerized action
  #minio:
    #image: bitnami/minio:latest
    #restart: always
    #volumes:
      #- /path/to/minio-persistence:/data
    #ports:
      #- "9000:9000"
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - action
  action:
      # current directory is where our projects root
      build: .
      # docker hub account repo
      image: 214168/handwrittingeffect 
      restart: always
      # expose ports
      ports:
      - "3000:3000"
      volumes:
      - //var/run/docker.sock:/var/run/docker.sock
